#!/bin/bash

# 设置基本的X环境变量
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="XFCE"
export XDG_MENU_PREFIX="xfce-"
export XDG_DATA_DIRS="/usr/share/xfce4:/usr/share/xfce:/usr/local/share:/usr/share"

# 启动基本的X服务
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# 启动窗口管理器
xrdb $HOME/.Xresources
xsetroot -solid grey

# 启动XFCE桌面环境
startxfce4 &